"""small changes

Revision ID: 343c24e7b3b4
Revises: 804928cc517e
Create Date: 2025-02-15 21:07:31.390070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '343c24e7b3b4'
down_revision: Union[str, None] = '804928cc517e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basho', 'special_prizes')
    op.create_foreign_key(None, 'match', 'basho', ['basho_id'], ['id'])
    op.drop_column('match', 'id')
    op.add_column('rikishi', sa.Column('basho_count', sa.Integer(), nullable=False))
    op.add_column('rikishi', sa.Column('basho_count_by_division', sa.JSON(), nullable=False))
    op.add_column('rikishi', sa.Column('yusho_count', sa.Integer(), nullable=False))
    op.add_column('rikishi', sa.Column('yusho_count_by_division', sa.JSON(), nullable=False))
    op.drop_column('rikishi', 'yusho')
    op.drop_column('rikishi', 'basho')
    op.drop_column('rikishi', 'basho_by_division')
    op.drop_column('rikishi', 'yusho_by_division')
    op.add_column('rikishi_basho', sa.Column('special_prize', sa.String(), nullable=True))
    op.add_column('rikishi_basho', sa.Column('yusho', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rikishi_basho', 'yusho')
    op.drop_column('rikishi_basho', 'special_prize')
    op.add_column('rikishi', sa.Column('yusho_by_division', sqlite.JSON(), nullable=False))
    op.add_column('rikishi', sa.Column('basho_by_division', sqlite.JSON(), nullable=False))
    op.add_column('rikishi', sa.Column('basho', sa.INTEGER(), nullable=False))
    op.add_column('rikishi', sa.Column('yusho', sa.INTEGER(), nullable=False))
    op.drop_column('rikishi', 'yusho_count_by_division')
    op.drop_column('rikishi', 'yusho_count')
    op.drop_column('rikishi', 'basho_count_by_division')
    op.drop_column('rikishi', 'basho_count')
    op.add_column('match', sa.Column('id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.add_column('basho', sa.Column('special_prizes', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
