"""init

Revision ID: 804928cc517e
Revises: 
Create Date: 2025-02-15 17:26:42.172687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804928cc517e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basho',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('special_prizes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rikishi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sumodb_id', sa.Integer(), nullable=True),
    sa.Column('nsk_id', sa.Integer(), nullable=False),
    sa.Column('shikona_en', sa.String(), nullable=False),
    sa.Column('shikona_jp', sa.String(), nullable=True),
    sa.Column('current_rank', sa.String(), nullable=False),
    sa.Column('heya', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('shusshin', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('debut', sa.String(), nullable=False),
    sa.Column('intai', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('absence_by_division', sa.JSON(), nullable=False),
    sa.Column('basho', sa.Integer(), nullable=False),
    sa.Column('basho_by_division', sa.JSON(), nullable=False),
    sa.Column('loss_by_division', sa.JSON(), nullable=False),
    sa.Column('sansho', sa.JSON(), nullable=False),
    sa.Column('total_absences', sa.Integer(), nullable=False),
    sa.Column('total_by_division', sa.JSON(), nullable=False),
    sa.Column('total_losses', sa.Integer(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.Column('wins_by_division', sa.JSON(), nullable=False),
    sa.Column('yusho', sa.Integer(), nullable=False),
    sa.Column('yusho_by_division', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('basho_id', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('match_no', sa.Integer(), nullable=False),
    sa.Column('east_id', sa.Integer(), nullable=False),
    sa.Column('east_shikona', sa.String(), nullable=False),
    sa.Column('east_rank', sa.String(), nullable=False),
    sa.Column('west_id', sa.Integer(), nullable=False),
    sa.Column('west_shikona', sa.String(), nullable=False),
    sa.Column('west_rank', sa.String(), nullable=False),
    sa.Column('kimarite', sa.String(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('winner_en', sa.String(), nullable=False),
    sa.Column('winner_jp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['east_id'], ['rikishi.id'], ),
    sa.ForeignKeyConstraint(['west_id'], ['rikishi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('basho_id', sa.String(), nullable=False),
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['basho_id'], ['basho.id'], ),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.PrimaryKeyConstraint('basho_id', 'rikishi_id')
    )
    op.create_table('rank',
    sa.Column('basho_id', sa.String(), nullable=False),
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('rank_value', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['basho_id'], ['basho.id'], ),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.PrimaryKeyConstraint('basho_id', 'rikishi_id')
    )
    op.create_table('rikishi_basho',
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('basho_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basho_id'], ['basho.id'], ),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.PrimaryKeyConstraint('rikishi_id', 'basho_id')
    )
    op.create_table('shikona',
    sa.Column('basho_id', sa.String(), nullable=False),
    sa.Column('rikishi_id', sa.Integer(), nullable=False),
    sa.Column('shikona_en', sa.String(), nullable=False),
    sa.Column('shikona_jp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['basho_id'], ['basho.id'], ),
    sa.ForeignKeyConstraint(['rikishi_id'], ['rikishi.id'], ),
    sa.PrimaryKeyConstraint('basho_id', 'rikishi_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shikona')
    op.drop_table('rikishi_basho')
    op.drop_table('rank')
    op.drop_table('measurement')
    op.drop_table('match')
    op.drop_table('rikishi')
    op.drop_table('basho')
    # ### end Alembic commands ###
